/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationsSeries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationsSeriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationsSeries
        //private ApplicationsSeries instance;

        public ApplicationsSeriesTests()
        {
            // TODO uncomment below to create an instance of ApplicationsSeries
            //instance = new ApplicationsSeries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationsSeries
        /// </summary>
        [Fact]
        public void ApplicationsSeriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationsSeries
            //Assert.IsType<ApplicationsSeries>(instance);
        }

        /// <summary>
        /// Test the property 'Datapoints'
        /// </summary>
        [Fact]
        public void DatapointsTest()
        {
            // TODO unit test for the property 'Datapoints'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
    }
}
