/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigGroupTheme
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigGroupThemeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigGroupTheme
        //private ConfigGroupTheme instance;

        public ConfigGroupThemeTests()
        {
            // TODO uncomment below to create an instance of ConfigGroupTheme
            //instance = new ConfigGroupTheme();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigGroupTheme
        /// </summary>
        [Fact]
        public void ConfigGroupThemeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigGroupTheme
            //Assert.IsType<ConfigGroupTheme>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Folder'
        /// </summary>
        [Fact]
        public void FolderTest()
        {
            // TODO unit test for the property 'Folder'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
