/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentModelsContentTypeProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentModelsContentTypePropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentModelsContentTypeProperty
        //private ContentModelsContentTypeProperty instance;

        public ContentModelsContentTypePropertyTests()
        {
            // TODO uncomment below to create an instance of ContentModelsContentTypeProperty
            //instance = new ContentModelsContentTypeProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentModelsContentTypeProperty
        /// </summary>
        [Fact]
        public void ContentModelsContentTypePropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentModelsContentTypeProperty
            //Assert.IsType<ContentModelsContentTypeProperty>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RootPropertyName'
        /// </summary>
        [Fact]
        public void RootPropertyNameTest()
        {
            // TODO unit test for the property 'RootPropertyName'
        }

        /// <summary>
        /// Test the property 'ReadableName'
        /// </summary>
        [Fact]
        public void ReadableNameTest()
        {
            // TODO unit test for the property 'ReadableName'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'PropertyDescription'
        /// </summary>
        [Fact]
        public void PropertyDescriptionTest()
        {
            // TODO unit test for the property 'PropertyDescription'
        }

        /// <summary>
        /// Test the property 'Localizable'
        /// </summary>
        [Fact]
        public void LocalizableTest()
        {
            // TODO unit test for the property 'Localizable'
        }

        /// <summary>
        /// Test the property 'Fallback'
        /// </summary>
        [Fact]
        public void FallbackTest()
        {
            // TODO unit test for the property 'Fallback'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Fact]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }

        /// <summary>
        /// Test the property 'IsTitle'
        /// </summary>
        [Fact]
        public void IsTitleTest()
        {
            // TODO unit test for the property 'IsTitle'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'MaxLength'
        /// </summary>
        [Fact]
        public void MaxLengthTest()
        {
            // TODO unit test for the property 'MaxLength'
        }

        /// <summary>
        /// Test the property 'MaxByteLength'
        /// </summary>
        [Fact]
        public void MaxByteLengthTest()
        {
            // TODO unit test for the property 'MaxByteLength'
        }

        /// <summary>
        /// Test the property 'MaxFileSize'
        /// </summary>
        [Fact]
        public void MaxFileSizeTest()
        {
            // TODO unit test for the property 'MaxFileSize'
        }

        /// <summary>
        /// Test the property 'Regexp'
        /// </summary>
        [Fact]
        public void RegexpTest()
        {
            // TODO unit test for the property 'Regexp'
        }

        /// <summary>
        /// Test the property 'ValidateAs'
        /// </summary>
        [Fact]
        public void ValidateAsTest()
        {
            // TODO unit test for the property 'ValidateAs'
        }

        /// <summary>
        /// Test the property 'RssAttribute'
        /// </summary>
        [Fact]
        public void RssAttributeTest()
        {
            // TODO unit test for the property 'RssAttribute'
        }

        /// <summary>
        /// Test the property 'VisibleDependency'
        /// </summary>
        [Fact]
        public void VisibleDependencyTest()
        {
            // TODO unit test for the property 'VisibleDependency'
        }

        /// <summary>
        /// Test the property 'VisibleOn'
        /// </summary>
        [Fact]
        public void VisibleOnTest()
        {
            // TODO unit test for the property 'VisibleOn'
        }

        /// <summary>
        /// Test the property 'Datatype'
        /// </summary>
        [Fact]
        public void DatatypeTest()
        {
            // TODO unit test for the property 'Datatype'
        }

        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

        /// <summary>
        /// Test the property 'ChildProperties'
        /// </summary>
        [Fact]
        public void ChildPropertiesTest()
        {
            // TODO unit test for the property 'ChildProperties'
        }

        /// <summary>
        /// Test the property 'ContentTypeAllowed'
        /// </summary>
        [Fact]
        public void ContentTypeAllowedTest()
        {
            // TODO unit test for the property 'ContentTypeAllowed'
        }

        /// <summary>
        /// Test the property 'BindToProperty'
        /// </summary>
        [Fact]
        public void BindToPropertyTest()
        {
            // TODO unit test for the property 'BindToProperty'
        }

        /// <summary>
        /// Test the property 'BoundRegex'
        /// </summary>
        [Fact]
        public void BoundRegexTest()
        {
            // TODO unit test for the property 'BoundRegex'
        }

        /// <summary>
        /// Test the property 'RepresentationSelection'
        /// </summary>
        [Fact]
        public void RepresentationSelectionTest()
        {
            // TODO unit test for the property 'RepresentationSelection'
        }

        /// <summary>
        /// Test the property 'DefaultValues'
        /// </summary>
        [Fact]
        public void DefaultValuesTest()
        {
            // TODO unit test for the property 'DefaultValues'
        }

        /// <summary>
        /// Test the property 'IsExternalAllowed'
        /// </summary>
        [Fact]
        public void IsExternalAllowedTest()
        {
            // TODO unit test for the property 'IsExternalAllowed'
        }

        /// <summary>
        /// Test the property 'PropertySection'
        /// </summary>
        [Fact]
        public void PropertySectionTest()
        {
            // TODO unit test for the property 'PropertySection'
        }

        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Fact]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

        /// <summary>
        /// Test the property 'Entitytype'
        /// </summary>
        [Fact]
        public void EntitytypeTest()
        {
            // TODO unit test for the property 'Entitytype'
        }

        /// <summary>
        /// Test the property 'IsCombo'
        /// </summary>
        [Fact]
        public void IsComboTest()
        {
            // TODO unit test for the property 'IsCombo'
        }

        /// <summary>
        /// Test the property 'SuppressProperty'
        /// </summary>
        [Fact]
        public void SuppressPropertyTest()
        {
            // TODO unit test for the property 'SuppressProperty'
        }

        /// <summary>
        /// Test the property 'LegalContentTypes'
        /// </summary>
        [Fact]
        public void LegalContentTypesTest()
        {
            // TODO unit test for the property 'LegalContentTypes'
        }

        /// <summary>
        /// Test the property 'RepresentationValidationString'
        /// </summary>
        [Fact]
        public void RepresentationValidationStringTest()
        {
            // TODO unit test for the property 'RepresentationValidationString'
        }

        /// <summary>
        /// Test the property 'MinWidth'
        /// </summary>
        [Fact]
        public void MinWidthTest()
        {
            // TODO unit test for the property 'MinWidth'
        }

        /// <summary>
        /// Test the property 'MaxWidth'
        /// </summary>
        [Fact]
        public void MaxWidthTest()
        {
            // TODO unit test for the property 'MaxWidth'
        }

        /// <summary>
        /// Test the property 'MinHeight'
        /// </summary>
        [Fact]
        public void MinHeightTest()
        {
            // TODO unit test for the property 'MinHeight'
        }

        /// <summary>
        /// Test the property 'MaxHeight'
        /// </summary>
        [Fact]
        public void MaxHeightTest()
        {
            // TODO unit test for the property 'MaxHeight'
        }

        /// <summary>
        /// Test the property 'IsVideo'
        /// </summary>
        [Fact]
        public void IsVideoTest()
        {
            // TODO unit test for the property 'IsVideo'
        }

        /// <summary>
        /// Test the property 'IsImage'
        /// </summary>
        [Fact]
        public void IsImageTest()
        {
            // TODO unit test for the property 'IsImage'
        }
    }
}
