/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentNewsArticleRssItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentNewsArticleRssItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentNewsArticleRssItem
        //private ContentNewsArticleRssItem instance;

        public ContentNewsArticleRssItemTests()
        {
            // TODO uncomment below to create an instance of ContentNewsArticleRssItem
            //instance = new ContentNewsArticleRssItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentNewsArticleRssItem
        /// </summary>
        [Fact]
        public void ContentNewsArticleRssItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentNewsArticleRssItem
            //Assert.IsType<ContentNewsArticleRssItem>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

        /// <summary>
        /// Test the property 'PubDate'
        /// </summary>
        [Fact]
        public void PubDateTest()
        {
            // TODO unit test for the property 'PubDate'
        }

        /// <summary>
        /// Test the property 'UniqueIdentifier'
        /// </summary>
        [Fact]
        public void UniqueIdentifierTest()
        {
            // TODO unit test for the property 'UniqueIdentifier'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'HtmlContent'
        /// </summary>
        [Fact]
        public void HtmlContentTest()
        {
            // TODO unit test for the property 'HtmlContent'
        }

        /// <summary>
        /// Test the property 'ImagePath'
        /// </summary>
        [Fact]
        public void ImagePathTest()
        {
            // TODO unit test for the property 'ImagePath'
        }

        /// <summary>
        /// Test the property 'OptionalMobileImagePath'
        /// </summary>
        [Fact]
        public void OptionalMobileImagePathTest()
        {
            // TODO unit test for the property 'OptionalMobileImagePath'
        }
    }
}
