/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyActivityMatchmakingBlockDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition
        //private DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition instance;

        public DestinyDefinitionsDestinyActivityMatchmakingBlockDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition
            //instance = new DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyActivityMatchmakingBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition
            //Assert.IsType<DestinyDefinitionsDestinyActivityMatchmakingBlockDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'IsMatchmade'
        /// </summary>
        [Fact]
        public void IsMatchmadeTest()
        {
            // TODO unit test for the property 'IsMatchmade'
        }

        /// <summary>
        /// Test the property 'MinParty'
        /// </summary>
        [Fact]
        public void MinPartyTest()
        {
            // TODO unit test for the property 'MinParty'
        }

        /// <summary>
        /// Test the property 'MaxParty'
        /// </summary>
        [Fact]
        public void MaxPartyTest()
        {
            // TODO unit test for the property 'MaxParty'
        }

        /// <summary>
        /// Test the property 'MaxPlayers'
        /// </summary>
        [Fact]
        public void MaxPlayersTest()
        {
            // TODO unit test for the property 'MaxPlayers'
        }

        /// <summary>
        /// Test the property 'RequiresGuardianOath'
        /// </summary>
        [Fact]
        public void RequiresGuardianOathTest()
        {
            // TODO unit test for the property 'RequiresGuardianOath'
        }
    }
}
