/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyDestinationDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyDestinationDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyDestinationDefinition
        //private DestinyDefinitionsDestinyDestinationDefinition instance;

        public DestinyDefinitionsDestinyDestinationDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyDestinationDefinition
            //instance = new DestinyDefinitionsDestinyDestinationDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyDestinationDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyDestinationDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyDestinationDefinition
            //Assert.IsType<DestinyDefinitionsDestinyDestinationDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'PlaceHash'
        /// </summary>
        [Fact]
        public void PlaceHashTest()
        {
            // TODO unit test for the property 'PlaceHash'
        }

        /// <summary>
        /// Test the property 'DefaultFreeroamActivityHash'
        /// </summary>
        [Fact]
        public void DefaultFreeroamActivityHashTest()
        {
            // TODO unit test for the property 'DefaultFreeroamActivityHash'
        }

        /// <summary>
        /// Test the property 'ActivityGraphEntries'
        /// </summary>
        [Fact]
        public void ActivityGraphEntriesTest()
        {
            // TODO unit test for the property 'ActivityGraphEntries'
        }

        /// <summary>
        /// Test the property 'BubbleSettings'
        /// </summary>
        [Fact]
        public void BubbleSettingsTest()
        {
            // TODO unit test for the property 'BubbleSettings'
        }

        /// <summary>
        /// Test the property 'Bubbles'
        /// </summary>
        [Fact]
        public void BubblesTest()
        {
            // TODO unit test for the property 'Bubbles'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
