/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyComponentsRecordsDestinyProfileRecordsComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsRecordsDestinyProfileRecordsComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsRecordsDestinyProfileRecordsComponent
        //private DestinyComponentsRecordsDestinyProfileRecordsComponent instance;

        public DestinyComponentsRecordsDestinyProfileRecordsComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyComponentsRecordsDestinyProfileRecordsComponent
            //instance = new DestinyComponentsRecordsDestinyProfileRecordsComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyComponentsRecordsDestinyProfileRecordsComponent
        /// </summary>
        [Fact]
        public void DestinyComponentsRecordsDestinyProfileRecordsComponentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyComponentsRecordsDestinyProfileRecordsComponent
            //Assert.IsType<DestinyComponentsRecordsDestinyProfileRecordsComponent>(instance);
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

        /// <summary>
        /// Test the property 'ActiveScore'
        /// </summary>
        [Fact]
        public void ActiveScoreTest()
        {
            // TODO unit test for the property 'ActiveScore'
        }

        /// <summary>
        /// Test the property 'LegacyScore'
        /// </summary>
        [Fact]
        public void LegacyScoreTest()
        {
            // TODO unit test for the property 'LegacyScore'
        }

        /// <summary>
        /// Test the property 'LifetimeScore'
        /// </summary>
        [Fact]
        public void LifetimeScoreTest()
        {
            // TODO unit test for the property 'LifetimeScore'
        }

        /// <summary>
        /// Test the property 'TrackedRecordHash'
        /// </summary>
        [Fact]
        public void TrackedRecordHashTest()
        {
            // TODO unit test for the property 'TrackedRecordHash'
        }

        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Fact]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

        /// <summary>
        /// Test the property 'RecordCategoriesRootNodeHash'
        /// </summary>
        [Fact]
        public void RecordCategoriesRootNodeHashTest()
        {
            // TODO unit test for the property 'RecordCategoriesRootNodeHash'
        }

        /// <summary>
        /// Test the property 'RecordSealsRootNodeHash'
        /// </summary>
        [Fact]
        public void RecordSealsRootNodeHashTest()
        {
            // TODO unit test for the property 'RecordSealsRootNodeHash'
        }
    }
}
