/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyResponsesDestinyCollectibleNodeDetailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyResponsesDestinyCollectibleNodeDetailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyResponsesDestinyCollectibleNodeDetailResponse
        //private DestinyResponsesDestinyCollectibleNodeDetailResponse instance;

        public DestinyResponsesDestinyCollectibleNodeDetailResponseTests()
        {
            // TODO uncomment below to create an instance of DestinyResponsesDestinyCollectibleNodeDetailResponse
            //instance = new DestinyResponsesDestinyCollectibleNodeDetailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyResponsesDestinyCollectibleNodeDetailResponse
        /// </summary>
        [Fact]
        public void DestinyResponsesDestinyCollectibleNodeDetailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyResponsesDestinyCollectibleNodeDetailResponse
            //Assert.IsType<DestinyResponsesDestinyCollectibleNodeDetailResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Collectibles'
        /// </summary>
        [Fact]
        public void CollectiblesTest()
        {
            // TODO unit test for the property 'Collectibles'
        }

        /// <summary>
        /// Test the property 'CollectibleItemComponents'
        /// </summary>
        [Fact]
        public void CollectibleItemComponentsTest()
        {
            // TODO unit test for the property 'CollectibleItemComponents'
        }
    }
}
