/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyArtifactsDestinyArtifactProfileScoped
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyArtifactsDestinyArtifactProfileScopedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyArtifactsDestinyArtifactProfileScoped
        //private DestinyArtifactsDestinyArtifactProfileScoped instance;

        public DestinyArtifactsDestinyArtifactProfileScopedTests()
        {
            // TODO uncomment below to create an instance of DestinyArtifactsDestinyArtifactProfileScoped
            //instance = new DestinyArtifactsDestinyArtifactProfileScoped();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyArtifactsDestinyArtifactProfileScoped
        /// </summary>
        [Fact]
        public void DestinyArtifactsDestinyArtifactProfileScopedInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyArtifactsDestinyArtifactProfileScoped
            //Assert.IsType<DestinyArtifactsDestinyArtifactProfileScoped>(instance);
        }

        /// <summary>
        /// Test the property 'ArtifactHash'
        /// </summary>
        [Fact]
        public void ArtifactHashTest()
        {
            // TODO unit test for the property 'ArtifactHash'
        }

        /// <summary>
        /// Test the property 'PointProgression'
        /// </summary>
        [Fact]
        public void PointProgressionTest()
        {
            // TODO unit test for the property 'PointProgression'
        }

        /// <summary>
        /// Test the property 'PointsAcquired'
        /// </summary>
        [Fact]
        public void PointsAcquiredTest()
        {
            // TODO unit test for the property 'PointsAcquired'
        }

        /// <summary>
        /// Test the property 'PowerBonusProgression'
        /// </summary>
        [Fact]
        public void PowerBonusProgressionTest()
        {
            // TODO unit test for the property 'PowerBonusProgression'
        }

        /// <summary>
        /// Test the property 'PowerBonus'
        /// </summary>
        [Fact]
        public void PowerBonusTest()
        {
            // TODO unit test for the property 'PowerBonus'
        }
    }
}
