/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyMilestonesDestinyMilestoneContentItemCategory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyMilestonesDestinyMilestoneContentItemCategoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyMilestonesDestinyMilestoneContentItemCategory
        //private DestinyMilestonesDestinyMilestoneContentItemCategory instance;

        public DestinyMilestonesDestinyMilestoneContentItemCategoryTests()
        {
            // TODO uncomment below to create an instance of DestinyMilestonesDestinyMilestoneContentItemCategory
            //instance = new DestinyMilestonesDestinyMilestoneContentItemCategory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyMilestonesDestinyMilestoneContentItemCategory
        /// </summary>
        [Fact]
        public void DestinyMilestonesDestinyMilestoneContentItemCategoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyMilestonesDestinyMilestoneContentItemCategory
            //Assert.IsType<DestinyMilestonesDestinyMilestoneContentItemCategory>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ItemHashes'
        /// </summary>
        [Fact]
        public void ItemHashesTest()
        {
            // TODO unit test for the property 'ItemHashes'
        }
    }
}
