/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsSourcesDestinyItemSourceDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsSourcesDestinyItemSourceDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsSourcesDestinyItemSourceDefinition
        //private DestinyDefinitionsSourcesDestinyItemSourceDefinition instance;

        public DestinyDefinitionsSourcesDestinyItemSourceDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsSourcesDestinyItemSourceDefinition
            //instance = new DestinyDefinitionsSourcesDestinyItemSourceDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsSourcesDestinyItemSourceDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsSourcesDestinyItemSourceDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsSourcesDestinyItemSourceDefinition
            //Assert.IsType<DestinyDefinitionsSourcesDestinyItemSourceDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }

        /// <summary>
        /// Test the property 'MinQuality'
        /// </summary>
        [Fact]
        public void MinQualityTest()
        {
            // TODO unit test for the property 'MinQuality'
        }

        /// <summary>
        /// Test the property 'MaxQuality'
        /// </summary>
        [Fact]
        public void MaxQualityTest()
        {
            // TODO unit test for the property 'MaxQuality'
        }

        /// <summary>
        /// Test the property 'MinLevelRequired'
        /// </summary>
        [Fact]
        public void MinLevelRequiredTest()
        {
            // TODO unit test for the property 'MinLevelRequired'
        }

        /// <summary>
        /// Test the property 'MaxLevelRequired'
        /// </summary>
        [Fact]
        public void MaxLevelRequiredTest()
        {
            // TODO unit test for the property 'MaxLevelRequired'
        }

        /// <summary>
        /// Test the property 'ComputedStats'
        /// </summary>
        [Fact]
        public void ComputedStatsTest()
        {
            // TODO unit test for the property 'ComputedStats'
        }

        /// <summary>
        /// Test the property 'SourceHashes'
        /// </summary>
        [Fact]
        public void SourceHashesTest()
        {
            // TODO unit test for the property 'SourceHashes'
        }
    }
}
