/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition
        //private DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition instance;

        public DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition
            //instance = new DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition
            //Assert.IsType<DestinyDefinitionsDestinyItemSocketEntryPlugItemRandomizedDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'CraftingRequirements'
        /// </summary>
        [Fact]
        public void CraftingRequirementsTest()
        {
            // TODO unit test for the property 'CraftingRequirements'
        }

        /// <summary>
        /// Test the property 'CurrentlyCanRoll'
        /// </summary>
        [Fact]
        public void CurrentlyCanRollTest()
        {
            // TODO unit test for the property 'CurrentlyCanRoll'
        }

        /// <summary>
        /// Test the property 'PlugItemHash'
        /// </summary>
        [Fact]
        public void PlugItemHashTest()
        {
            // TODO unit test for the property 'PlugItemHash'
        }
    }
}
