/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDestinyTalentNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyTalentNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyTalentNode
        //private DestinyDestinyTalentNode instance;

        public DestinyDestinyTalentNodeTests()
        {
            // TODO uncomment below to create an instance of DestinyDestinyTalentNode
            //instance = new DestinyDestinyTalentNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDestinyTalentNode
        /// </summary>
        [Fact]
        public void DestinyDestinyTalentNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDestinyTalentNode
            //Assert.IsType<DestinyDestinyTalentNode>(instance);
        }

        /// <summary>
        /// Test the property 'NodeIndex'
        /// </summary>
        [Fact]
        public void NodeIndexTest()
        {
            // TODO unit test for the property 'NodeIndex'
        }

        /// <summary>
        /// Test the property 'NodeHash'
        /// </summary>
        [Fact]
        public void NodeHashTest()
        {
            // TODO unit test for the property 'NodeHash'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'IsActivated'
        /// </summary>
        [Fact]
        public void IsActivatedTest()
        {
            // TODO unit test for the property 'IsActivated'
        }

        /// <summary>
        /// Test the property 'StepIndex'
        /// </summary>
        [Fact]
        public void StepIndexTest()
        {
            // TODO unit test for the property 'StepIndex'
        }

        /// <summary>
        /// Test the property 'MaterialsToUpgrade'
        /// </summary>
        [Fact]
        public void MaterialsToUpgradeTest()
        {
            // TODO unit test for the property 'MaterialsToUpgrade'
        }

        /// <summary>
        /// Test the property 'ActivationGridLevel'
        /// </summary>
        [Fact]
        public void ActivationGridLevelTest()
        {
            // TODO unit test for the property 'ActivationGridLevel'
        }

        /// <summary>
        /// Test the property 'ProgressPercent'
        /// </summary>
        [Fact]
        public void ProgressPercentTest()
        {
            // TODO unit test for the property 'ProgressPercent'
        }

        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Fact]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }

        /// <summary>
        /// Test the property 'NodeStatsBlock'
        /// </summary>
        [Fact]
        public void NodeStatsBlockTest()
        {
            // TODO unit test for the property 'NodeStatsBlock'
        }
    }
}
