/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDestinyProgressionResetEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyProgressionResetEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyProgressionResetEntry
        //private DestinyDestinyProgressionResetEntry instance;

        public DestinyDestinyProgressionResetEntryTests()
        {
            // TODO uncomment below to create an instance of DestinyDestinyProgressionResetEntry
            //instance = new DestinyDestinyProgressionResetEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDestinyProgressionResetEntry
        /// </summary>
        [Fact]
        public void DestinyDestinyProgressionResetEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDestinyProgressionResetEntry
            //Assert.IsType<DestinyDestinyProgressionResetEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Season'
        /// </summary>
        [Fact]
        public void SeasonTest()
        {
            // TODO unit test for the property 'Season'
        }

        /// <summary>
        /// Test the property 'Resets'
        /// </summary>
        [Fact]
        public void ResetsTest()
        {
            // TODO unit test for the property 'Resets'
        }
    }
}
