/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyRequestsActionsDestinyInsertPlugsActionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyRequestsActionsDestinyInsertPlugsActionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyRequestsActionsDestinyInsertPlugsActionRequest
        //private DestinyRequestsActionsDestinyInsertPlugsActionRequest instance;

        public DestinyRequestsActionsDestinyInsertPlugsActionRequestTests()
        {
            // TODO uncomment below to create an instance of DestinyRequestsActionsDestinyInsertPlugsActionRequest
            //instance = new DestinyRequestsActionsDestinyInsertPlugsActionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyRequestsActionsDestinyInsertPlugsActionRequest
        /// </summary>
        [Fact]
        public void DestinyRequestsActionsDestinyInsertPlugsActionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyRequestsActionsDestinyInsertPlugsActionRequest
            //Assert.IsType<DestinyRequestsActionsDestinyInsertPlugsActionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ActionToken'
        /// </summary>
        [Fact]
        public void ActionTokenTest()
        {
            // TODO unit test for the property 'ActionToken'
        }

        /// <summary>
        /// Test the property 'ItemInstanceId'
        /// </summary>
        [Fact]
        public void ItemInstanceIdTest()
        {
            // TODO unit test for the property 'ItemInstanceId'
        }

        /// <summary>
        /// Test the property 'Plug'
        /// </summary>
        [Fact]
        public void PlugTest()
        {
            // TODO unit test for the property 'Plug'
        }

        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Fact]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }

        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Fact]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }
    }
}
