/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyConstantsDestinyEnvironmentLocationMapping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyConstantsDestinyEnvironmentLocationMappingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyConstantsDestinyEnvironmentLocationMapping
        //private DestinyConstantsDestinyEnvironmentLocationMapping instance;

        public DestinyConstantsDestinyEnvironmentLocationMappingTests()
        {
            // TODO uncomment below to create an instance of DestinyConstantsDestinyEnvironmentLocationMapping
            //instance = new DestinyConstantsDestinyEnvironmentLocationMapping();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyConstantsDestinyEnvironmentLocationMapping
        /// </summary>
        [Fact]
        public void DestinyConstantsDestinyEnvironmentLocationMappingInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyConstantsDestinyEnvironmentLocationMapping
            //Assert.IsType<DestinyConstantsDestinyEnvironmentLocationMapping>(instance);
        }

        /// <summary>
        /// Test the property 'LocationHash'
        /// </summary>
        [Fact]
        public void LocationHashTest()
        {
            // TODO unit test for the property 'LocationHash'
        }

        /// <summary>
        /// Test the property 'ActivationSource'
        /// </summary>
        [Fact]
        public void ActivationSourceTest()
        {
            // TODO unit test for the property 'ActivationSource'
        }

        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Fact]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }

        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Fact]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }

        /// <summary>
        /// Test the property 'ActivityHash'
        /// </summary>
        [Fact]
        public void ActivityHashTest()
        {
            // TODO unit test for the property 'ActivityHash'
        }
    }
}
