/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsSocketsDestinySocketTypeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsSocketsDestinySocketTypeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsSocketsDestinySocketTypeDefinition
        //private DestinyDefinitionsSocketsDestinySocketTypeDefinition instance;

        public DestinyDefinitionsSocketsDestinySocketTypeDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsSocketsDestinySocketTypeDefinition
            //instance = new DestinyDefinitionsSocketsDestinySocketTypeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsSocketsDestinySocketTypeDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsSocketsDestinySocketTypeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsSocketsDestinySocketTypeDefinition
            //Assert.IsType<DestinyDefinitionsSocketsDestinySocketTypeDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'InsertAction'
        /// </summary>
        [Fact]
        public void InsertActionTest()
        {
            // TODO unit test for the property 'InsertAction'
        }

        /// <summary>
        /// Test the property 'PlugWhitelist'
        /// </summary>
        [Fact]
        public void PlugWhitelistTest()
        {
            // TODO unit test for the property 'PlugWhitelist'
        }

        /// <summary>
        /// Test the property 'SocketCategoryHash'
        /// </summary>
        [Fact]
        public void SocketCategoryHashTest()
        {
            // TODO unit test for the property 'SocketCategoryHash'
        }

        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Fact]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }

        /// <summary>
        /// Test the property 'AlwaysRandomizeSockets'
        /// </summary>
        [Fact]
        public void AlwaysRandomizeSocketsTest()
        {
            // TODO unit test for the property 'AlwaysRandomizeSockets'
        }

        /// <summary>
        /// Test the property 'IsPreviewEnabled'
        /// </summary>
        [Fact]
        public void IsPreviewEnabledTest()
        {
            // TODO unit test for the property 'IsPreviewEnabled'
        }

        /// <summary>
        /// Test the property 'HideDuplicateReusablePlugs'
        /// </summary>
        [Fact]
        public void HideDuplicateReusablePlugsTest()
        {
            // TODO unit test for the property 'HideDuplicateReusablePlugs'
        }

        /// <summary>
        /// Test the property 'OverridesUiAppearance'
        /// </summary>
        [Fact]
        public void OverridesUiAppearanceTest()
        {
            // TODO unit test for the property 'OverridesUiAppearance'
        }

        /// <summary>
        /// Test the property 'AvoidDuplicatesOnInitialization'
        /// </summary>
        [Fact]
        public void AvoidDuplicatesOnInitializationTest()
        {
            // TODO unit test for the property 'AvoidDuplicatesOnInitialization'
        }

        /// <summary>
        /// Test the property 'CurrencyScalars'
        /// </summary>
        [Fact]
        public void CurrencyScalarsTest()
        {
            // TODO unit test for the property 'CurrencyScalars'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
