/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyVendorDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorDefinition
        //private DestinyDefinitionsDestinyVendorDefinition instance;

        public DestinyDefinitionsDestinyVendorDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorDefinition
            //instance = new DestinyDefinitionsDestinyVendorDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyVendorDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyVendorDefinition
            //Assert.IsType<DestinyDefinitionsDestinyVendorDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'VendorProgressionType'
        /// </summary>
        [Fact]
        public void VendorProgressionTypeTest()
        {
            // TODO unit test for the property 'VendorProgressionType'
        }

        /// <summary>
        /// Test the property 'BuyString'
        /// </summary>
        [Fact]
        public void BuyStringTest()
        {
            // TODO unit test for the property 'BuyString'
        }

        /// <summary>
        /// Test the property 'SellString'
        /// </summary>
        [Fact]
        public void SellStringTest()
        {
            // TODO unit test for the property 'SellString'
        }

        /// <summary>
        /// Test the property 'DisplayItemHash'
        /// </summary>
        [Fact]
        public void DisplayItemHashTest()
        {
            // TODO unit test for the property 'DisplayItemHash'
        }

        /// <summary>
        /// Test the property 'InhibitBuying'
        /// </summary>
        [Fact]
        public void InhibitBuyingTest()
        {
            // TODO unit test for the property 'InhibitBuying'
        }

        /// <summary>
        /// Test the property 'InhibitSelling'
        /// </summary>
        [Fact]
        public void InhibitSellingTest()
        {
            // TODO unit test for the property 'InhibitSelling'
        }

        /// <summary>
        /// Test the property 'FactionHash'
        /// </summary>
        [Fact]
        public void FactionHashTest()
        {
            // TODO unit test for the property 'FactionHash'
        }

        /// <summary>
        /// Test the property 'ResetIntervalMinutes'
        /// </summary>
        [Fact]
        public void ResetIntervalMinutesTest()
        {
            // TODO unit test for the property 'ResetIntervalMinutes'
        }

        /// <summary>
        /// Test the property 'ResetOffsetMinutes'
        /// </summary>
        [Fact]
        public void ResetOffsetMinutesTest()
        {
            // TODO unit test for the property 'ResetOffsetMinutes'
        }

        /// <summary>
        /// Test the property 'FailureStrings'
        /// </summary>
        [Fact]
        public void FailureStringsTest()
        {
            // TODO unit test for the property 'FailureStrings'
        }

        /// <summary>
        /// Test the property 'UnlockRanges'
        /// </summary>
        [Fact]
        public void UnlockRangesTest()
        {
            // TODO unit test for the property 'UnlockRanges'
        }

        /// <summary>
        /// Test the property 'VendorIdentifier'
        /// </summary>
        [Fact]
        public void VendorIdentifierTest()
        {
            // TODO unit test for the property 'VendorIdentifier'
        }

        /// <summary>
        /// Test the property 'VendorPortrait'
        /// </summary>
        [Fact]
        public void VendorPortraitTest()
        {
            // TODO unit test for the property 'VendorPortrait'
        }

        /// <summary>
        /// Test the property 'VendorBanner'
        /// </summary>
        [Fact]
        public void VendorBannerTest()
        {
            // TODO unit test for the property 'VendorBanner'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Fact]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }

        /// <summary>
        /// Test the property 'VendorSubcategoryIdentifier'
        /// </summary>
        [Fact]
        public void VendorSubcategoryIdentifierTest()
        {
            // TODO unit test for the property 'VendorSubcategoryIdentifier'
        }

        /// <summary>
        /// Test the property 'ConsolidateCategories'
        /// </summary>
        [Fact]
        public void ConsolidateCategoriesTest()
        {
            // TODO unit test for the property 'ConsolidateCategories'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }

        /// <summary>
        /// Test the property 'OriginalCategories'
        /// </summary>
        [Fact]
        public void OriginalCategoriesTest()
        {
            // TODO unit test for the property 'OriginalCategories'
        }

        /// <summary>
        /// Test the property 'DisplayCategories'
        /// </summary>
        [Fact]
        public void DisplayCategoriesTest()
        {
            // TODO unit test for the property 'DisplayCategories'
        }

        /// <summary>
        /// Test the property 'Interactions'
        /// </summary>
        [Fact]
        public void InteractionsTest()
        {
            // TODO unit test for the property 'Interactions'
        }

        /// <summary>
        /// Test the property 'InventoryFlyouts'
        /// </summary>
        [Fact]
        public void InventoryFlyoutsTest()
        {
            // TODO unit test for the property 'InventoryFlyouts'
        }

        /// <summary>
        /// Test the property 'ItemList'
        /// </summary>
        [Fact]
        public void ItemListTest()
        {
            // TODO unit test for the property 'ItemList'
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

        /// <summary>
        /// Test the property 'AcceptedItems'
        /// </summary>
        [Fact]
        public void AcceptedItemsTest()
        {
            // TODO unit test for the property 'AcceptedItems'
        }

        /// <summary>
        /// Test the property 'ReturnWithVendorRequest'
        /// </summary>
        [Fact]
        public void ReturnWithVendorRequestTest()
        {
            // TODO unit test for the property 'ReturnWithVendorRequest'
        }

        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Fact]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }

        /// <summary>
        /// Test the property 'IgnoreSaleItemHashes'
        /// </summary>
        [Fact]
        public void IgnoreSaleItemHashesTest()
        {
            // TODO unit test for the property 'IgnoreSaleItemHashes'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
