/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyEntitiesItemsDestinyItemComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyEntitiesItemsDestinyItemComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyEntitiesItemsDestinyItemComponent
        //private DestinyEntitiesItemsDestinyItemComponent instance;

        public DestinyEntitiesItemsDestinyItemComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyEntitiesItemsDestinyItemComponent
            //instance = new DestinyEntitiesItemsDestinyItemComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyEntitiesItemsDestinyItemComponent
        /// </summary>
        [Fact]
        public void DestinyEntitiesItemsDestinyItemComponentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyEntitiesItemsDestinyItemComponent
            //Assert.IsType<DestinyEntitiesItemsDestinyItemComponent>(instance);
        }

        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Fact]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }

        /// <summary>
        /// Test the property 'ItemInstanceId'
        /// </summary>
        [Fact]
        public void ItemInstanceIdTest()
        {
            // TODO unit test for the property 'ItemInstanceId'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'BindStatus'
        /// </summary>
        [Fact]
        public void BindStatusTest()
        {
            // TODO unit test for the property 'BindStatus'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'BucketHash'
        /// </summary>
        [Fact]
        public void BucketHashTest()
        {
            // TODO unit test for the property 'BucketHash'
        }

        /// <summary>
        /// Test the property 'TransferStatus'
        /// </summary>
        [Fact]
        public void TransferStatusTest()
        {
            // TODO unit test for the property 'TransferStatus'
        }

        /// <summary>
        /// Test the property 'Lockable'
        /// </summary>
        [Fact]
        public void LockableTest()
        {
            // TODO unit test for the property 'Lockable'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'OverrideStyleItemHash'
        /// </summary>
        [Fact]
        public void OverrideStyleItemHashTest()
        {
            // TODO unit test for the property 'OverrideStyleItemHash'
        }

        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }

        /// <summary>
        /// Test the property 'IsWrapper'
        /// </summary>
        [Fact]
        public void IsWrapperTest()
        {
            // TODO unit test for the property 'IsWrapper'
        }

        /// <summary>
        /// Test the property 'TooltipNotificationIndexes'
        /// </summary>
        [Fact]
        public void TooltipNotificationIndexesTest()
        {
            // TODO unit test for the property 'TooltipNotificationIndexes'
        }

        /// <summary>
        /// Test the property 'MetricHash'
        /// </summary>
        [Fact]
        public void MetricHashTest()
        {
            // TODO unit test for the property 'MetricHash'
        }

        /// <summary>
        /// Test the property 'MetricObjective'
        /// </summary>
        [Fact]
        public void MetricObjectiveTest()
        {
            // TODO unit test for the property 'MetricObjective'
        }

        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }

        /// <summary>
        /// Test the property 'ItemValueVisibility'
        /// </summary>
        [Fact]
        public void ItemValueVisibilityTest()
        {
            // TODO unit test for the property 'ItemValueVisibility'
        }
    }
}
