/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyComponentsStringVariablesDestinyStringVariablesComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyComponentsStringVariablesDestinyStringVariablesComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyComponentsStringVariablesDestinyStringVariablesComponent
        //private DestinyComponentsStringVariablesDestinyStringVariablesComponent instance;

        public DestinyComponentsStringVariablesDestinyStringVariablesComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyComponentsStringVariablesDestinyStringVariablesComponent
            //instance = new DestinyComponentsStringVariablesDestinyStringVariablesComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyComponentsStringVariablesDestinyStringVariablesComponent
        /// </summary>
        [Fact]
        public void DestinyComponentsStringVariablesDestinyStringVariablesComponentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyComponentsStringVariablesDestinyStringVariablesComponent
            //Assert.IsType<DestinyComponentsStringVariablesDestinyStringVariablesComponent>(instance);
        }

        /// <summary>
        /// Test the property 'IntegerValuesByHash'
        /// </summary>
        [Fact]
        public void IntegerValuesByHashTest()
        {
            // TODO unit test for the property 'IntegerValuesByHash'
        }
    }
}
