/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsCollectiblesDestinyCollectibleDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsCollectiblesDestinyCollectibleDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsCollectiblesDestinyCollectibleDefinition
        //private DestinyDefinitionsCollectiblesDestinyCollectibleDefinition instance;

        public DestinyDefinitionsCollectiblesDestinyCollectibleDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsCollectiblesDestinyCollectibleDefinition
            //instance = new DestinyDefinitionsCollectiblesDestinyCollectibleDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsCollectiblesDestinyCollectibleDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsCollectiblesDestinyCollectibleDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsCollectiblesDestinyCollectibleDefinition
            //Assert.IsType<DestinyDefinitionsCollectiblesDestinyCollectibleDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'SourceString'
        /// </summary>
        [Fact]
        public void SourceStringTest()
        {
            // TODO unit test for the property 'SourceString'
        }

        /// <summary>
        /// Test the property 'SourceHash'
        /// </summary>
        [Fact]
        public void SourceHashTest()
        {
            // TODO unit test for the property 'SourceHash'
        }

        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Fact]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }

        /// <summary>
        /// Test the property 'AcquisitionInfo'
        /// </summary>
        [Fact]
        public void AcquisitionInfoTest()
        {
            // TODO unit test for the property 'AcquisitionInfo'
        }

        /// <summary>
        /// Test the property 'StateInfo'
        /// </summary>
        [Fact]
        public void StateInfoTest()
        {
            // TODO unit test for the property 'StateInfo'
        }

        /// <summary>
        /// Test the property 'PresentationInfo'
        /// </summary>
        [Fact]
        public void PresentationInfoTest()
        {
            // TODO unit test for the property 'PresentationInfo'
        }

        /// <summary>
        /// Test the property 'PresentationNodeType'
        /// </summary>
        [Fact]
        public void PresentationNodeTypeTest()
        {
            // TODO unit test for the property 'PresentationNodeType'
        }

        /// <summary>
        /// Test the property 'TraitIds'
        /// </summary>
        [Fact]
        public void TraitIdsTest()
        {
            // TODO unit test for the property 'TraitIds'
        }

        /// <summary>
        /// Test the property 'TraitHashes'
        /// </summary>
        [Fact]
        public void TraitHashesTest()
        {
            // TODO unit test for the property 'TraitHashes'
        }

        /// <summary>
        /// Test the property 'ParentNodeHashes'
        /// </summary>
        [Fact]
        public void ParentNodeHashesTest()
        {
            // TODO unit test for the property 'ParentNodeHashes'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
