/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyActivityChallengeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyActivityChallengeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyActivityChallengeDefinition
        //private DestinyDefinitionsDestinyActivityChallengeDefinition instance;

        public DestinyDefinitionsDestinyActivityChallengeDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyActivityChallengeDefinition
            //instance = new DestinyDefinitionsDestinyActivityChallengeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyActivityChallengeDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyActivityChallengeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyActivityChallengeDefinition
            //Assert.IsType<DestinyDefinitionsDestinyActivityChallengeDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Fact]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }

        /// <summary>
        /// Test the property 'DummyRewards'
        /// </summary>
        [Fact]
        public void DummyRewardsTest()
        {
            // TODO unit test for the property 'DummyRewards'
        }
    }
}
