/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsPresentationDestinyPresentationNodeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
        //private DestinyDefinitionsPresentationDestinyPresentationNodeDefinition instance;

        public DestinyDefinitionsPresentationDestinyPresentationNodeDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
            //instance = new DestinyDefinitionsPresentationDestinyPresentationNodeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsPresentationDestinyPresentationNodeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsPresentationDestinyPresentationNodeDefinition
            //Assert.IsType<DestinyDefinitionsPresentationDestinyPresentationNodeDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'OriginalIcon'
        /// </summary>
        [Fact]
        public void OriginalIconTest()
        {
            // TODO unit test for the property 'OriginalIcon'
        }

        /// <summary>
        /// Test the property 'RootViewIcon'
        /// </summary>
        [Fact]
        public void RootViewIconTest()
        {
            // TODO unit test for the property 'RootViewIcon'
        }

        /// <summary>
        /// Test the property 'NodeType'
        /// </summary>
        [Fact]
        public void NodeTypeTest()
        {
            // TODO unit test for the property 'NodeType'
        }

        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Fact]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }

        /// <summary>
        /// Test the property 'ObjectiveHash'
        /// </summary>
        [Fact]
        public void ObjectiveHashTest()
        {
            // TODO unit test for the property 'ObjectiveHash'
        }

        /// <summary>
        /// Test the property 'CompletionRecordHash'
        /// </summary>
        [Fact]
        public void CompletionRecordHashTest()
        {
            // TODO unit test for the property 'CompletionRecordHash'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'DisplayStyle'
        /// </summary>
        [Fact]
        public void DisplayStyleTest()
        {
            // TODO unit test for the property 'DisplayStyle'
        }

        /// <summary>
        /// Test the property 'ScreenStyle'
        /// </summary>
        [Fact]
        public void ScreenStyleTest()
        {
            // TODO unit test for the property 'ScreenStyle'
        }

        /// <summary>
        /// Test the property 'Requirements'
        /// </summary>
        [Fact]
        public void RequirementsTest()
        {
            // TODO unit test for the property 'Requirements'
        }

        /// <summary>
        /// Test the property 'DisableChildSubscreenNavigation'
        /// </summary>
        [Fact]
        public void DisableChildSubscreenNavigationTest()
        {
            // TODO unit test for the property 'DisableChildSubscreenNavigation'
        }

        /// <summary>
        /// Test the property 'MaxCategoryRecordScore'
        /// </summary>
        [Fact]
        public void MaxCategoryRecordScoreTest()
        {
            // TODO unit test for the property 'MaxCategoryRecordScore'
        }

        /// <summary>
        /// Test the property 'PresentationNodeType'
        /// </summary>
        [Fact]
        public void PresentationNodeTypeTest()
        {
            // TODO unit test for the property 'PresentationNodeType'
        }

        /// <summary>
        /// Test the property 'TraitIds'
        /// </summary>
        [Fact]
        public void TraitIdsTest()
        {
            // TODO unit test for the property 'TraitIds'
        }

        /// <summary>
        /// Test the property 'TraitHashes'
        /// </summary>
        [Fact]
        public void TraitHashesTest()
        {
            // TODO unit test for the property 'TraitHashes'
        }

        /// <summary>
        /// Test the property 'ParentNodeHashes'
        /// </summary>
        [Fact]
        public void ParentNodeHashesTest()
        {
            // TODO unit test for the property 'ParentNodeHashes'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
