/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDestinyStat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDestinyStatTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDestinyStat
        //private DestinyDestinyStat instance;

        public DestinyDestinyStatTests()
        {
            // TODO uncomment below to create an instance of DestinyDestinyStat
            //instance = new DestinyDestinyStat();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDestinyStat
        /// </summary>
        [Fact]
        public void DestinyDestinyStatInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDestinyStat
            //Assert.IsType<DestinyDestinyStat>(instance);
        }

        /// <summary>
        /// Test the property 'StatHash'
        /// </summary>
        [Fact]
        public void StatHashTest()
        {
            // TODO unit test for the property 'StatHash'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
