/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition
        //private DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition instance;

        public DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition
            //instance = new DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition
            //Assert.IsType<DestinyDefinitionsMilestonesDestinyMilestoneRewardCategoryDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'CategoryHash'
        /// </summary>
        [Fact]
        public void CategoryHashTest()
        {
            // TODO unit test for the property 'CategoryHash'
        }

        /// <summary>
        /// Test the property 'CategoryIdentifier'
        /// </summary>
        [Fact]
        public void CategoryIdentifierTest()
        {
            // TODO unit test for the property 'CategoryIdentifier'
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'RewardEntries'
        /// </summary>
        [Fact]
        public void RewardEntriesTest()
        {
            // TODO unit test for the property 'RewardEntries'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
