/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorAcceptedItemDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsDestinyVendorAcceptedItemDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorAcceptedItemDefinition
        //private DestinyDefinitionsDestinyVendorAcceptedItemDefinition instance;

        public DestinyDefinitionsDestinyVendorAcceptedItemDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorAcceptedItemDefinition
            //instance = new DestinyDefinitionsDestinyVendorAcceptedItemDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorAcceptedItemDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsDestinyVendorAcceptedItemDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsDestinyVendorAcceptedItemDefinition
            //Assert.IsType<DestinyDefinitionsDestinyVendorAcceptedItemDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'AcceptedInventoryBucketHash'
        /// </summary>
        [Fact]
        public void AcceptedInventoryBucketHashTest()
        {
            // TODO unit test for the property 'AcceptedInventoryBucketHash'
        }

        /// <summary>
        /// Test the property 'DestinationInventoryBucketHash'
        /// </summary>
        [Fact]
        public void DestinationInventoryBucketHashTest()
        {
            // TODO unit test for the property 'DestinationInventoryBucketHash'
        }
    }
}
