/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsItemsDestinyItemTierTypeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsItemsDestinyItemTierTypeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsItemsDestinyItemTierTypeDefinition
        //private DestinyDefinitionsItemsDestinyItemTierTypeDefinition instance;

        public DestinyDefinitionsItemsDestinyItemTierTypeDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsItemsDestinyItemTierTypeDefinition
            //instance = new DestinyDefinitionsItemsDestinyItemTierTypeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsItemsDestinyItemTierTypeDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsItemsDestinyItemTierTypeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsItemsDestinyItemTierTypeDefinition
            //Assert.IsType<DestinyDefinitionsItemsDestinyItemTierTypeDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'InfusionProcess'
        /// </summary>
        [Fact]
        public void InfusionProcessTest()
        {
            // TODO unit test for the property 'InfusionProcess'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
