/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition
        //private DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition instance;

        public DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinitionTests()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition
            //instance = new DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition
        /// </summary>
        [Fact]
        public void DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition
            //Assert.IsType<DestinyDefinitionsLoadoutsDestinyLoadoutConstantsDefinition>(instance);
        }

        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Fact]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }

        /// <summary>
        /// Test the property 'WhiteIconImagePath'
        /// </summary>
        [Fact]
        public void WhiteIconImagePathTest()
        {
            // TODO unit test for the property 'WhiteIconImagePath'
        }

        /// <summary>
        /// Test the property 'BlackIconImagePath'
        /// </summary>
        [Fact]
        public void BlackIconImagePathTest()
        {
            // TODO unit test for the property 'BlackIconImagePath'
        }

        /// <summary>
        /// Test the property 'LoadoutCountPerCharacter'
        /// </summary>
        [Fact]
        public void LoadoutCountPerCharacterTest()
        {
            // TODO unit test for the property 'LoadoutCountPerCharacter'
        }

        /// <summary>
        /// Test the property 'LoadoutPreviewFilterOutSocketCategoryHashes'
        /// </summary>
        [Fact]
        public void LoadoutPreviewFilterOutSocketCategoryHashesTest()
        {
            // TODO unit test for the property 'LoadoutPreviewFilterOutSocketCategoryHashes'
        }

        /// <summary>
        /// Test the property 'LoadoutPreviewFilterOutSocketTypeHashes'
        /// </summary>
        [Fact]
        public void LoadoutPreviewFilterOutSocketTypeHashesTest()
        {
            // TODO unit test for the property 'LoadoutPreviewFilterOutSocketTypeHashes'
        }

        /// <summary>
        /// Test the property 'LoadoutNameHashes'
        /// </summary>
        [Fact]
        public void LoadoutNameHashesTest()
        {
            // TODO unit test for the property 'LoadoutNameHashes'
        }

        /// <summary>
        /// Test the property 'LoadoutIconHashes'
        /// </summary>
        [Fact]
        public void LoadoutIconHashesTest()
        {
            // TODO unit test for the property 'LoadoutIconHashes'
        }

        /// <summary>
        /// Test the property 'LoadoutColorHashes'
        /// </summary>
        [Fact]
        public void LoadoutColorHashesTest()
        {
            // TODO unit test for the property 'LoadoutColorHashes'
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Fact]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }
    }
}
