/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyRequestsActionsDestinyItemStateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyRequestsActionsDestinyItemStateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyRequestsActionsDestinyItemStateRequest
        //private DestinyRequestsActionsDestinyItemStateRequest instance;

        public DestinyRequestsActionsDestinyItemStateRequestTests()
        {
            // TODO uncomment below to create an instance of DestinyRequestsActionsDestinyItemStateRequest
            //instance = new DestinyRequestsActionsDestinyItemStateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyRequestsActionsDestinyItemStateRequest
        /// </summary>
        [Fact]
        public void DestinyRequestsActionsDestinyItemStateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyRequestsActionsDestinyItemStateRequest
            //Assert.IsType<DestinyRequestsActionsDestinyItemStateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Fact]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }

        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Fact]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }

        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Fact]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }
    }
}
