/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyEntitiesProfilesDestinyProfileComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyEntitiesProfilesDestinyProfileComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyEntitiesProfilesDestinyProfileComponent
        //private DestinyEntitiesProfilesDestinyProfileComponent instance;

        public DestinyEntitiesProfilesDestinyProfileComponentTests()
        {
            // TODO uncomment below to create an instance of DestinyEntitiesProfilesDestinyProfileComponent
            //instance = new DestinyEntitiesProfilesDestinyProfileComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyEntitiesProfilesDestinyProfileComponent
        /// </summary>
        [Fact]
        public void DestinyEntitiesProfilesDestinyProfileComponentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyEntitiesProfilesDestinyProfileComponent
            //Assert.IsType<DestinyEntitiesProfilesDestinyProfileComponent>(instance);
        }

        /// <summary>
        /// Test the property 'UserInfo'
        /// </summary>
        [Fact]
        public void UserInfoTest()
        {
            // TODO unit test for the property 'UserInfo'
        }

        /// <summary>
        /// Test the property 'DateLastPlayed'
        /// </summary>
        [Fact]
        public void DateLastPlayedTest()
        {
            // TODO unit test for the property 'DateLastPlayed'
        }

        /// <summary>
        /// Test the property 'VersionsOwned'
        /// </summary>
        [Fact]
        public void VersionsOwnedTest()
        {
            // TODO unit test for the property 'VersionsOwned'
        }

        /// <summary>
        /// Test the property 'CharacterIds'
        /// </summary>
        [Fact]
        public void CharacterIdsTest()
        {
            // TODO unit test for the property 'CharacterIds'
        }

        /// <summary>
        /// Test the property 'SeasonHashes'
        /// </summary>
        [Fact]
        public void SeasonHashesTest()
        {
            // TODO unit test for the property 'SeasonHashes'
        }

        /// <summary>
        /// Test the property 'EventCardHashesOwned'
        /// </summary>
        [Fact]
        public void EventCardHashesOwnedTest()
        {
            // TODO unit test for the property 'EventCardHashesOwned'
        }

        /// <summary>
        /// Test the property 'CurrentSeasonHash'
        /// </summary>
        [Fact]
        public void CurrentSeasonHashTest()
        {
            // TODO unit test for the property 'CurrentSeasonHash'
        }

        /// <summary>
        /// Test the property 'CurrentSeasonRewardPowerCap'
        /// </summary>
        [Fact]
        public void CurrentSeasonRewardPowerCapTest()
        {
            // TODO unit test for the property 'CurrentSeasonRewardPowerCap'
        }

        /// <summary>
        /// Test the property 'ActiveEventCardHash'
        /// </summary>
        [Fact]
        public void ActiveEventCardHashTest()
        {
            // TODO unit test for the property 'ActiveEventCardHash'
        }

        /// <summary>
        /// Test the property 'CurrentGuardianRank'
        /// </summary>
        [Fact]
        public void CurrentGuardianRankTest()
        {
            // TODO unit test for the property 'CurrentGuardianRank'
        }

        /// <summary>
        /// Test the property 'LifetimeHighestGuardianRank'
        /// </summary>
        [Fact]
        public void LifetimeHighestGuardianRankTest()
        {
            // TODO unit test for the property 'LifetimeHighestGuardianRank'
        }
    }
}
