/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DestinyItemComponentSetOfuint32
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DestinyItemComponentSetOfuint32Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DestinyItemComponentSetOfuint32
        //private DestinyItemComponentSetOfuint32 instance;

        public DestinyItemComponentSetOfuint32Tests()
        {
            // TODO uncomment below to create an instance of DestinyItemComponentSetOfuint32
            //instance = new DestinyItemComponentSetOfuint32();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DestinyItemComponentSetOfuint32
        /// </summary>
        [Fact]
        public void DestinyItemComponentSetOfuint32InstanceTest()
        {
            // TODO uncomment below to test "IsType" DestinyItemComponentSetOfuint32
            //Assert.IsType<DestinyItemComponentSetOfuint32>(instance);
        }

        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Fact]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }

        /// <summary>
        /// Test the property 'RenderData'
        /// </summary>
        [Fact]
        public void RenderDataTest()
        {
            // TODO unit test for the property 'RenderData'
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

        /// <summary>
        /// Test the property 'Sockets'
        /// </summary>
        [Fact]
        public void SocketsTest()
        {
            // TODO unit test for the property 'Sockets'
        }

        /// <summary>
        /// Test the property 'ReusablePlugs'
        /// </summary>
        [Fact]
        public void ReusablePlugsTest()
        {
            // TODO unit test for the property 'ReusablePlugs'
        }

        /// <summary>
        /// Test the property 'PlugObjectives'
        /// </summary>
        [Fact]
        public void PlugObjectivesTest()
        {
            // TODO unit test for the property 'PlugObjectives'
        }

        /// <summary>
        /// Test the property 'TalentGrids'
        /// </summary>
        [Fact]
        public void TalentGridsTest()
        {
            // TODO unit test for the property 'TalentGrids'
        }

        /// <summary>
        /// Test the property 'PlugStates'
        /// </summary>
        [Fact]
        public void PlugStatesTest()
        {
            // TODO unit test for the property 'PlugStates'
        }

        /// <summary>
        /// Test the property 'Objectives'
        /// </summary>
        [Fact]
        public void ObjectivesTest()
        {
            // TODO unit test for the property 'Objectives'
        }

        /// <summary>
        /// Test the property 'Perks'
        /// </summary>
        [Fact]
        public void PerksTest()
        {
            // TODO unit test for the property 'Perks'
        }
    }
}
