/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
        //private DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent instance;

        public DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponentTests()
        {
            // TODO uncomment below to create an instance of DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
            //instance = new DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
        /// </summary>
        [Fact]
        public void DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponentInstanceTest()
        {
            // TODO uncomment below to test "IsType" DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent
            //Assert.IsType<DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Fact]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }

        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
    }
}
