/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GroupsV2ClanBanner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2ClanBannerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupsV2ClanBanner
        //private GroupsV2ClanBanner instance;

        public GroupsV2ClanBannerTests()
        {
            // TODO uncomment below to create an instance of GroupsV2ClanBanner
            //instance = new GroupsV2ClanBanner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupsV2ClanBanner
        /// </summary>
        [Fact]
        public void GroupsV2ClanBannerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupsV2ClanBanner
            //Assert.IsType<GroupsV2ClanBanner>(instance);
        }

        /// <summary>
        /// Test the property 'DecalId'
        /// </summary>
        [Fact]
        public void DecalIdTest()
        {
            // TODO unit test for the property 'DecalId'
        }

        /// <summary>
        /// Test the property 'DecalColorId'
        /// </summary>
        [Fact]
        public void DecalColorIdTest()
        {
            // TODO unit test for the property 'DecalColorId'
        }

        /// <summary>
        /// Test the property 'DecalBackgroundColorId'
        /// </summary>
        [Fact]
        public void DecalBackgroundColorIdTest()
        {
            // TODO unit test for the property 'DecalBackgroundColorId'
        }

        /// <summary>
        /// Test the property 'GonfalonId'
        /// </summary>
        [Fact]
        public void GonfalonIdTest()
        {
            // TODO unit test for the property 'GonfalonId'
        }

        /// <summary>
        /// Test the property 'GonfalonColorId'
        /// </summary>
        [Fact]
        public void GonfalonColorIdTest()
        {
            // TODO unit test for the property 'GonfalonColorId'
        }

        /// <summary>
        /// Test the property 'GonfalonDetailId'
        /// </summary>
        [Fact]
        public void GonfalonDetailIdTest()
        {
            // TODO unit test for the property 'GonfalonDetailId'
        }

        /// <summary>
        /// Test the property 'GonfalonDetailColorId'
        /// </summary>
        [Fact]
        public void GonfalonDetailColorIdTest()
        {
            // TODO unit test for the property 'GonfalonDetailColorId'
        }
    }
}
