/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GroupsV2GroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupsV2GroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupResponse
        //private GroupsV2GroupResponse instance;

        public GroupsV2GroupResponseTests()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupResponse
            //instance = new GroupsV2GroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupsV2GroupResponse
        /// </summary>
        [Fact]
        public void GroupsV2GroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupsV2GroupResponse
            //Assert.IsType<GroupsV2GroupResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

        /// <summary>
        /// Test the property 'Founder'
        /// </summary>
        [Fact]
        public void FounderTest()
        {
            // TODO unit test for the property 'Founder'
        }

        /// <summary>
        /// Test the property 'AlliedIds'
        /// </summary>
        [Fact]
        public void AlliedIdsTest()
        {
            // TODO unit test for the property 'AlliedIds'
        }

        /// <summary>
        /// Test the property 'ParentGroup'
        /// </summary>
        [Fact]
        public void ParentGroupTest()
        {
            // TODO unit test for the property 'ParentGroup'
        }

        /// <summary>
        /// Test the property 'AllianceStatus'
        /// </summary>
        [Fact]
        public void AllianceStatusTest()
        {
            // TODO unit test for the property 'AllianceStatus'
        }

        /// <summary>
        /// Test the property 'GroupJoinInviteCount'
        /// </summary>
        [Fact]
        public void GroupJoinInviteCountTest()
        {
            // TODO unit test for the property 'GroupJoinInviteCount'
        }

        /// <summary>
        /// Test the property 'CurrentUserMembershipsInactiveForDestiny'
        /// </summary>
        [Fact]
        public void CurrentUserMembershipsInactiveForDestinyTest()
        {
            // TODO unit test for the property 'CurrentUserMembershipsInactiveForDestiny'
        }

        /// <summary>
        /// Test the property 'CurrentUserMemberMap'
        /// </summary>
        [Fact]
        public void CurrentUserMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserMemberMap'
        }

        /// <summary>
        /// Test the property 'CurrentUserPotentialMemberMap'
        /// </summary>
        [Fact]
        public void CurrentUserPotentialMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserPotentialMemberMap'
        }
    }
}
