/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResultOfContentItemPublicContract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultOfContentItemPublicContractTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResultOfContentItemPublicContract
        //private SearchResultOfContentItemPublicContract instance;

        public SearchResultOfContentItemPublicContractTests()
        {
            // TODO uncomment below to create an instance of SearchResultOfContentItemPublicContract
            //instance = new SearchResultOfContentItemPublicContract();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResultOfContentItemPublicContract
        /// </summary>
        [Fact]
        public void SearchResultOfContentItemPublicContractInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResultOfContentItemPublicContract
            //Assert.IsType<SearchResultOfContentItemPublicContract>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

        /// <summary>
        /// Test the property 'TotalResults'
        /// </summary>
        [Fact]
        public void TotalResultsTest()
        {
            // TODO unit test for the property 'TotalResults'
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'ReplacementContinuationToken'
        /// </summary>
        [Fact]
        public void ReplacementContinuationTokenTest()
        {
            // TODO unit test for the property 'ReplacementContinuationToken'
        }

        /// <summary>
        /// Test the property 'UseTotalResults'
        /// </summary>
        [Fact]
        public void UseTotalResultsTest()
        {
            // TODO unit test for the property 'UseTotalResults'
        }
    }
}
