/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserGeneralUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserGeneralUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserGeneralUser
        //private UserGeneralUser instance;

        public UserGeneralUserTests()
        {
            // TODO uncomment below to create an instance of UserGeneralUser
            //instance = new UserGeneralUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserGeneralUser
        /// </summary>
        [Fact]
        public void UserGeneralUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserGeneralUser
            //Assert.IsType<UserGeneralUser>(instance);
        }

        /// <summary>
        /// Test the property 'MembershipId'
        /// </summary>
        [Fact]
        public void MembershipIdTest()
        {
            // TODO unit test for the property 'MembershipId'
        }

        /// <summary>
        /// Test the property 'UniqueName'
        /// </summary>
        [Fact]
        public void UniqueNameTest()
        {
            // TODO unit test for the property 'UniqueName'
        }

        /// <summary>
        /// Test the property 'NormalizedName'
        /// </summary>
        [Fact]
        public void NormalizedNameTest()
        {
            // TODO unit test for the property 'NormalizedName'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'ProfilePicture'
        /// </summary>
        [Fact]
        public void ProfilePictureTest()
        {
            // TODO unit test for the property 'ProfilePicture'
        }

        /// <summary>
        /// Test the property 'ProfileTheme'
        /// </summary>
        [Fact]
        public void ProfileThemeTest()
        {
            // TODO unit test for the property 'ProfileTheme'
        }

        /// <summary>
        /// Test the property 'UserTitle'
        /// </summary>
        [Fact]
        public void UserTitleTest()
        {
            // TODO unit test for the property 'UserTitle'
        }

        /// <summary>
        /// Test the property 'SuccessMessageFlags'
        /// </summary>
        [Fact]
        public void SuccessMessageFlagsTest()
        {
            // TODO unit test for the property 'SuccessMessageFlags'
        }

        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

        /// <summary>
        /// Test the property 'About'
        /// </summary>
        [Fact]
        public void AboutTest()
        {
            // TODO unit test for the property 'About'
        }

        /// <summary>
        /// Test the property 'FirstAccess'
        /// </summary>
        [Fact]
        public void FirstAccessTest()
        {
            // TODO unit test for the property 'FirstAccess'
        }

        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Fact]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }

        /// <summary>
        /// Test the property 'LegacyPortalUID'
        /// </summary>
        [Fact]
        public void LegacyPortalUIDTest()
        {
            // TODO unit test for the property 'LegacyPortalUID'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'PsnDisplayName'
        /// </summary>
        [Fact]
        public void PsnDisplayNameTest()
        {
            // TODO unit test for the property 'PsnDisplayName'
        }

        /// <summary>
        /// Test the property 'XboxDisplayName'
        /// </summary>
        [Fact]
        public void XboxDisplayNameTest()
        {
            // TODO unit test for the property 'XboxDisplayName'
        }

        /// <summary>
        /// Test the property 'FbDisplayName'
        /// </summary>
        [Fact]
        public void FbDisplayNameTest()
        {
            // TODO unit test for the property 'FbDisplayName'
        }

        /// <summary>
        /// Test the property 'ShowActivity'
        /// </summary>
        [Fact]
        public void ShowActivityTest()
        {
            // TODO unit test for the property 'ShowActivity'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'LocaleInheritDefault'
        /// </summary>
        [Fact]
        public void LocaleInheritDefaultTest()
        {
            // TODO unit test for the property 'LocaleInheritDefault'
        }

        /// <summary>
        /// Test the property 'LastBanReportId'
        /// </summary>
        [Fact]
        public void LastBanReportIdTest()
        {
            // TODO unit test for the property 'LastBanReportId'
        }

        /// <summary>
        /// Test the property 'ShowGroupMessaging'
        /// </summary>
        [Fact]
        public void ShowGroupMessagingTest()
        {
            // TODO unit test for the property 'ShowGroupMessaging'
        }

        /// <summary>
        /// Test the property 'ProfilePicturePath'
        /// </summary>
        [Fact]
        public void ProfilePicturePathTest()
        {
            // TODO unit test for the property 'ProfilePicturePath'
        }

        /// <summary>
        /// Test the property 'ProfilePictureWidePath'
        /// </summary>
        [Fact]
        public void ProfilePictureWidePathTest()
        {
            // TODO unit test for the property 'ProfilePictureWidePath'
        }

        /// <summary>
        /// Test the property 'ProfileThemeName'
        /// </summary>
        [Fact]
        public void ProfileThemeNameTest()
        {
            // TODO unit test for the property 'ProfileThemeName'
        }

        /// <summary>
        /// Test the property 'UserTitleDisplay'
        /// </summary>
        [Fact]
        public void UserTitleDisplayTest()
        {
            // TODO unit test for the property 'UserTitleDisplay'
        }

        /// <summary>
        /// Test the property 'StatusText'
        /// </summary>
        [Fact]
        public void StatusTextTest()
        {
            // TODO unit test for the property 'StatusText'
        }

        /// <summary>
        /// Test the property 'StatusDate'
        /// </summary>
        [Fact]
        public void StatusDateTest()
        {
            // TODO unit test for the property 'StatusDate'
        }

        /// <summary>
        /// Test the property 'ProfileBanExpire'
        /// </summary>
        [Fact]
        public void ProfileBanExpireTest()
        {
            // TODO unit test for the property 'ProfileBanExpire'
        }

        /// <summary>
        /// Test the property 'BlizzardDisplayName'
        /// </summary>
        [Fact]
        public void BlizzardDisplayNameTest()
        {
            // TODO unit test for the property 'BlizzardDisplayName'
        }

        /// <summary>
        /// Test the property 'SteamDisplayName'
        /// </summary>
        [Fact]
        public void SteamDisplayNameTest()
        {
            // TODO unit test for the property 'SteamDisplayName'
        }

        /// <summary>
        /// Test the property 'StadiaDisplayName'
        /// </summary>
        [Fact]
        public void StadiaDisplayNameTest()
        {
            // TODO unit test for the property 'StadiaDisplayName'
        }

        /// <summary>
        /// Test the property 'TwitchDisplayName'
        /// </summary>
        [Fact]
        public void TwitchDisplayNameTest()
        {
            // TODO unit test for the property 'TwitchDisplayName'
        }

        /// <summary>
        /// Test the property 'CachedBungieGlobalDisplayName'
        /// </summary>
        [Fact]
        public void CachedBungieGlobalDisplayNameTest()
        {
            // TODO unit test for the property 'CachedBungieGlobalDisplayName'
        }

        /// <summary>
        /// Test the property 'CachedBungieGlobalDisplayNameCode'
        /// </summary>
        [Fact]
        public void CachedBungieGlobalDisplayNameCodeTest()
        {
            // TODO unit test for the property 'CachedBungieGlobalDisplayNameCode'
        }

        /// <summary>
        /// Test the property 'EgsDisplayName'
        /// </summary>
        [Fact]
        public void EgsDisplayNameTest()
        {
            // TODO unit test for the property 'EgsDisplayName'
        }
    }
}
