/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserHardLinkedUserMembership
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserHardLinkedUserMembershipTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserHardLinkedUserMembership
        //private UserHardLinkedUserMembership instance;

        public UserHardLinkedUserMembershipTests()
        {
            // TODO uncomment below to create an instance of UserHardLinkedUserMembership
            //instance = new UserHardLinkedUserMembership();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserHardLinkedUserMembership
        /// </summary>
        [Fact]
        public void UserHardLinkedUserMembershipInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserHardLinkedUserMembership
            //Assert.IsType<UserHardLinkedUserMembership>(instance);
        }

        /// <summary>
        /// Test the property 'MembershipType'
        /// </summary>
        [Fact]
        public void MembershipTypeTest()
        {
            // TODO unit test for the property 'MembershipType'
        }

        /// <summary>
        /// Test the property 'MembershipId'
        /// </summary>
        [Fact]
        public void MembershipIdTest()
        {
            // TODO unit test for the property 'MembershipId'
        }

        /// <summary>
        /// Test the property 'CrossSaveOverriddenType'
        /// </summary>
        [Fact]
        public void CrossSaveOverriddenTypeTest()
        {
            // TODO unit test for the property 'CrossSaveOverriddenType'
        }

        /// <summary>
        /// Test the property 'CrossSaveOverriddenMembershipId'
        /// </summary>
        [Fact]
        public void CrossSaveOverriddenMembershipIdTest()
        {
            // TODO unit test for the property 'CrossSaveOverriddenMembershipId'
        }
    }
}
