/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DestinyDefinitionsDestinyGearArtArrangementReference
    /// </summary>
    [DataContract(Name = "Destiny.Definitions.DestinyGearArtArrangementReference")]
    public partial class DestinyDefinitionsDestinyGearArtArrangementReference : IEquatable<DestinyDefinitionsDestinyGearArtArrangementReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyDefinitionsDestinyGearArtArrangementReference" /> class.
        /// </summary>
        /// <param name="classHash">classHash.</param>
        /// <param name="artArrangementHash">artArrangementHash.</param>
        public DestinyDefinitionsDestinyGearArtArrangementReference(int classHash = default(int), int artArrangementHash = default(int))
        {
            this.ClassHash = classHash;
            this.ArtArrangementHash = artArrangementHash;
        }

        /// <summary>
        /// Gets or Sets ClassHash
        /// </summary>
        [DataMember(Name = "classHash", EmitDefaultValue = false)]
        public int ClassHash { get; set; }

        /// <summary>
        /// Gets or Sets ArtArrangementHash
        /// </summary>
        [DataMember(Name = "artArrangementHash", EmitDefaultValue = false)]
        public int ArtArrangementHash { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DestinyDefinitionsDestinyGearArtArrangementReference {\n");
            sb.Append("  ClassHash: ").Append(ClassHash).Append("\n");
            sb.Append("  ArtArrangementHash: ").Append(ArtArrangementHash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyDefinitionsDestinyGearArtArrangementReference);
        }

        /// <summary>
        /// Returns true if DestinyDefinitionsDestinyGearArtArrangementReference instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyDefinitionsDestinyGearArtArrangementReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyDefinitionsDestinyGearArtArrangementReference input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ClassHash == input.ClassHash ||
                    this.ClassHash.Equals(input.ClassHash)
                ) && 
                (
                    this.ArtArrangementHash == input.ArtArrangementHash ||
                    this.ArtArrangementHash.Equals(input.ArtArrangementHash)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ClassHash.GetHashCode();
                hashCode = (hashCode * 59) + this.ArtArrangementHash.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
