/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry
    /// </summary>
    [DataContract(Name = "Destiny.Definitions.Presentation.DestinyPresentationNodeCollectibleChildEntry")]
    public partial class DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry : IEquatable<DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry" /> class.
        /// </summary>
        /// <param name="collectibleHash">collectibleHash.</param>
        /// <param name="nodeDisplayPriority">Use this value to sort the presentation node children in ascending order..</param>
        public DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry(int collectibleHash = default(int), int nodeDisplayPriority = default(int))
        {
            this.CollectibleHash = collectibleHash;
            this.NodeDisplayPriority = nodeDisplayPriority;
        }

        /// <summary>
        /// Gets or Sets CollectibleHash
        /// </summary>
        [DataMember(Name = "collectibleHash", EmitDefaultValue = false)]
        public int CollectibleHash { get; set; }

        /// <summary>
        /// Use this value to sort the presentation node children in ascending order.
        /// </summary>
        /// <value>Use this value to sort the presentation node children in ascending order.</value>
        [DataMember(Name = "nodeDisplayPriority", EmitDefaultValue = false)]
        public int NodeDisplayPriority { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry {\n");
            sb.Append("  CollectibleHash: ").Append(CollectibleHash).Append("\n");
            sb.Append("  NodeDisplayPriority: ").Append(NodeDisplayPriority).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry);
        }

        /// <summary>
        /// Returns true if DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry instances are equal
        /// </summary>
        /// <param name="input">Instance of DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DestinyDefinitionsPresentationDestinyPresentationNodeCollectibleChildEntry input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CollectibleHash == input.CollectibleHash ||
                    this.CollectibleHash.Equals(input.CollectibleHash)
                ) && 
                (
                    this.NodeDisplayPriority == input.NodeDisplayPriority ||
                    this.NodeDisplayPriority.Equals(input.NodeDisplayPriority)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CollectibleHash.GetHashCode();
                hashCode = (hashCode * 59) + this.NodeDisplayPriority.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
