/*
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.18.0
 * Contact: support@bungie.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SocialFriendsPlatformFriend
    /// </summary>
    [DataContract(Name = "Social.Friends.PlatformFriend")]
    public partial class SocialFriendsPlatformFriend : IEquatable<SocialFriendsPlatformFriend>, IValidatableObject
    {
        /// <summary>
        /// Defines DestinyMembershipType
        /// </summary>
        public enum DestinyMembershipTypeEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_2 for value: 2
            /// </summary>
            NUMBER_2 = 2,

            /// <summary>
            /// Enum NUMBER_3 for value: 3
            /// </summary>
            NUMBER_3 = 3,

            /// <summary>
            /// Enum NUMBER_4 for value: 4
            /// </summary>
            NUMBER_4 = 4,

            /// <summary>
            /// Enum NUMBER_5 for value: 5
            /// </summary>
            NUMBER_5 = 5,

            /// <summary>
            /// Enum NUMBER_6 for value: 6
            /// </summary>
            NUMBER_6 = 6,

            /// <summary>
            /// Enum NUMBER_10 for value: 10
            /// </summary>
            NUMBER_10 = 10,

            /// <summary>
            /// Enum NUMBER_254 for value: 254
            /// </summary>
            NUMBER_254 = 254,

            /// <summary>
            /// Enum NUMBER_MINUS_1 for value: -1
            /// </summary>
            NUMBER_MINUS_1 = -1
        }


        /// <summary>
        /// Gets or Sets DestinyMembershipType
        /// </summary>
        [DataMember(Name = "destinyMembershipType", EmitDefaultValue = true)]
        public DestinyMembershipTypeEnum? DestinyMembershipType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SocialFriendsPlatformFriend" /> class.
        /// </summary>
        /// <param name="platformDisplayName">platformDisplayName.</param>
        /// <param name="friendPlatform">friendPlatform.</param>
        /// <param name="destinyMembershipId">destinyMembershipId.</param>
        /// <param name="destinyMembershipType">destinyMembershipType.</param>
        /// <param name="bungieNetMembershipId">bungieNetMembershipId.</param>
        /// <param name="bungieGlobalDisplayName">bungieGlobalDisplayName.</param>
        /// <param name="bungieGlobalDisplayNameCode">bungieGlobalDisplayNameCode.</param>
        public SocialFriendsPlatformFriend(string platformDisplayName = default(string), int friendPlatform = default(int), long? destinyMembershipId = default(long?), DestinyMembershipTypeEnum? destinyMembershipType = default(DestinyMembershipTypeEnum?), long? bungieNetMembershipId = default(long?), string bungieGlobalDisplayName = default(string), int? bungieGlobalDisplayNameCode = default(int?))
        {
            this.PlatformDisplayName = platformDisplayName;
            this.FriendPlatform = friendPlatform;
            this.DestinyMembershipId = destinyMembershipId;
            this.DestinyMembershipType = destinyMembershipType;
            this.BungieNetMembershipId = bungieNetMembershipId;
            this.BungieGlobalDisplayName = bungieGlobalDisplayName;
            this.BungieGlobalDisplayNameCode = bungieGlobalDisplayNameCode;
        }

        /// <summary>
        /// Gets or Sets PlatformDisplayName
        /// </summary>
        [DataMember(Name = "platformDisplayName", EmitDefaultValue = false)]
        public string PlatformDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets FriendPlatform
        /// </summary>
        [DataMember(Name = "friendPlatform", EmitDefaultValue = false)]
        public int FriendPlatform { get; set; }

        /// <summary>
        /// Gets or Sets DestinyMembershipId
        /// </summary>
        [DataMember(Name = "destinyMembershipId", EmitDefaultValue = true)]
        public long? DestinyMembershipId { get; set; }

        /// <summary>
        /// Gets or Sets BungieNetMembershipId
        /// </summary>
        [DataMember(Name = "bungieNetMembershipId", EmitDefaultValue = true)]
        public long? BungieNetMembershipId { get; set; }

        /// <summary>
        /// Gets or Sets BungieGlobalDisplayName
        /// </summary>
        [DataMember(Name = "bungieGlobalDisplayName", EmitDefaultValue = false)]
        public string BungieGlobalDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets BungieGlobalDisplayNameCode
        /// </summary>
        [DataMember(Name = "bungieGlobalDisplayNameCode", EmitDefaultValue = true)]
        public int? BungieGlobalDisplayNameCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SocialFriendsPlatformFriend {\n");
            sb.Append("  PlatformDisplayName: ").Append(PlatformDisplayName).Append("\n");
            sb.Append("  FriendPlatform: ").Append(FriendPlatform).Append("\n");
            sb.Append("  DestinyMembershipId: ").Append(DestinyMembershipId).Append("\n");
            sb.Append("  DestinyMembershipType: ").Append(DestinyMembershipType).Append("\n");
            sb.Append("  BungieNetMembershipId: ").Append(BungieNetMembershipId).Append("\n");
            sb.Append("  BungieGlobalDisplayName: ").Append(BungieGlobalDisplayName).Append("\n");
            sb.Append("  BungieGlobalDisplayNameCode: ").Append(BungieGlobalDisplayNameCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SocialFriendsPlatformFriend);
        }

        /// <summary>
        /// Returns true if SocialFriendsPlatformFriend instances are equal
        /// </summary>
        /// <param name="input">Instance of SocialFriendsPlatformFriend to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SocialFriendsPlatformFriend input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PlatformDisplayName == input.PlatformDisplayName ||
                    (this.PlatformDisplayName != null &&
                    this.PlatformDisplayName.Equals(input.PlatformDisplayName))
                ) && 
                (
                    this.FriendPlatform == input.FriendPlatform ||
                    this.FriendPlatform.Equals(input.FriendPlatform)
                ) && 
                (
                    this.DestinyMembershipId == input.DestinyMembershipId ||
                    (this.DestinyMembershipId != null &&
                    this.DestinyMembershipId.Equals(input.DestinyMembershipId))
                ) && 
                (
                    this.DestinyMembershipType == input.DestinyMembershipType ||
                    this.DestinyMembershipType.Equals(input.DestinyMembershipType)
                ) && 
                (
                    this.BungieNetMembershipId == input.BungieNetMembershipId ||
                    (this.BungieNetMembershipId != null &&
                    this.BungieNetMembershipId.Equals(input.BungieNetMembershipId))
                ) && 
                (
                    this.BungieGlobalDisplayName == input.BungieGlobalDisplayName ||
                    (this.BungieGlobalDisplayName != null &&
                    this.BungieGlobalDisplayName.Equals(input.BungieGlobalDisplayName))
                ) && 
                (
                    this.BungieGlobalDisplayNameCode == input.BungieGlobalDisplayNameCode ||
                    (this.BungieGlobalDisplayNameCode != null &&
                    this.BungieGlobalDisplayNameCode.Equals(input.BungieGlobalDisplayNameCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlatformDisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.PlatformDisplayName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.FriendPlatform.GetHashCode();
                if (this.DestinyMembershipId != null)
                {
                    hashCode = (hashCode * 59) + this.DestinyMembershipId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DestinyMembershipType.GetHashCode();
                if (this.BungieNetMembershipId != null)
                {
                    hashCode = (hashCode * 59) + this.BungieNetMembershipId.GetHashCode();
                }
                if (this.BungieGlobalDisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.BungieGlobalDisplayName.GetHashCode();
                }
                if (this.BungieGlobalDisplayNameCode != null)
                {
                    hashCode = (hashCode * 59) + this.BungieGlobalDisplayNameCode.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
